package com.example.signalclone.localization

import androidx.compose.ui.unit.LayoutDirection
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class AppLanguage(
    val code: String,
    val nativeName: String,
    val englishName: String,
    val layoutDirection: LayoutDirection,
    val flagEmoji: String
) {
    ARABIC("ar", "العربية", "Arabic", LayoutDirection.Rtl, "🇸🇦"),
    ENGLISH("en", "English", "English", LayoutDirection.Ltr, "🇺🇸"),
    FRENCH("fr", "Français", "French", LayoutDirection.Ltr, "🇫🇷"),
    SPANISH("es", "Español", "Spanish", LayoutDirection.Ltr, "🇪🇸"),
    GERMAN("de", "Deutsch", "German", LayoutDirection.Ltr, "🇩🇪"),
    TURKISH("tr", "Türkçe", "Turkish", LayoutDirection.Ltr, "🇹🇷")
}

object LocalizationManager {

    // Default to Arabic as requested by user, or English
    private val _currentLanguage = MutableStateFlow(AppLanguage.ARABIC)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    fun setLanguage(lang: AppLanguage) {
        _currentLanguage.value = lang
    }

    private val translations = mapOf(
        "ar" to mapOf(
            "app_name" to "Adam Signal",
            "app_subtitle" to "تشفير فائق من تطوير Adam Dev",
            "chats" to "المحادثات",
            "calls" to "المكالمات",
            "stories" to "المستجدات",
            "settings" to "الإعدادات",
            "all" to "الكل",
            "pinned" to "المثبتة",
            "unread" to "غير المقروءة",
            "direct" to "مباشرة",
            "groups" to "المجموعات",
            "search_hint" to "بحث في المحادثات والرسائل...",
            "new_chat" to "محادثة جديدة",
            "new_group" to "مجموعة جديدة",
            "new_broadcast" to "رسالة جماعية جديدة",
            "starred_messages" to "الرسائل المميزة بنجمة",
            "linked_devices" to "الأجهزة المرتبطة",
            "account" to "الحساب",
            "account_subtitle" to "إشعارات الأمان، مفاتيح المرور، تغيير الرقم",
            "privacy" to "الخصوصية",
            "privacy_subtitle" to "آخر ظهور، قفل الشاشة، مؤقت الرسائل ذاتية الاختفاء",
            "chats_settings" to "الدردشات",
            "chats_settings_subtitle" to "المظهر، خلفية الشاشة، سجل الدردشات، النسخ الاحتياطي",
            "notifications" to "الإشعارات",
            "notifications_subtitle" to "نغمات الرسائل والمجموعات، الاهتزاز، الإشعارات ذات الأولوية",
            "storage_and_data" to "التخزين والبيانات",
            "storage_and_data_subtitle" to "استخدام الشبكة، إدارة التخزين، التنزيل التلقائي",
            "app_language" to "لغة التطبيق",
            "app_language_subtitle" to "العربية (لغة الجهاز المحددة)",
            "help" to "المساعدة",
            "help_subtitle" to "مركز المساعدة، اتصل بنا، سياسة الخصوصية والشروط",
            "invite_friend" to "دعوة صديق",
            "profile" to "الملف الشخصي",
            "profile_and_settings" to "الملف الشخصي والإعدادات",
            "sign_out" to "تسجيل الخروج",
            "about_status" to "الأخبار والوصف",
            "default_status" to "أهلاً بك! أنا أستخدم Adam Signal بتشفير فائق 🛡️",
            "phone_number" to "رقم الهاتف",
            "username" to "اسم المستخدم",
            "verified_account" to "حساب موثق رسمياً",
            "creator_badge" to "المطور ومهندس الأمان",
            "qr_code" to "رمز QR",
            "my_code" to "رمزي الشخصي",
            "scan_code" to "مسح الرمز",
            "share_code" to "مشاركة الرمز",
            "reset_code" to "إعادة تعيين الرمز",
            "qr_description" to "رمز QR خاص بك مشفر بأمان. يمكن للآخرين مسحه لبدء محادثة مشفرة معك فوراً.",
            "star" to "تمييز بنجمة",
            "unstar" to "إزالة النجمة",
            "reply" to "رد",
            "forward" to "إعادة توجيه",
            "copy" to "نسخ النص",
            "delete" to "حذف الرسالة",
            "typing" to "يكتب الآن...",
            "online" to "متصل الآن",
            "offline" to "غير متصل",
            "type_a_message" to "اكتب رسالة مشفرة...",
            "hold_to_record" to "اضغط للتسجيل الصوتي",
            "recording" to "جارٍ التسجيل...",
            "safety_number" to "رقم الأمان المشفر",
            "disappearing_messages" to "الرسائل ذاتية الاختفاء",
            "chat_wallpaper" to "خلفية الدردشة",
            "clear_chat" to "مسح محتوى الدردشة",
            "no_starred_messages" to "لا توجد رسائل مميزة بنجمة حتى الآن",
            "starred_hint" to "المس أي رسالة مع الاستمرار في أي دردشة لتمييزها بنجمة وتسهيل العثور عليها لاحقاً.",
            "theme" to "المظهر",
            "theme_light" to "فاتح",
            "theme_dark" to "داكن",
            "theme_system" to "افتراضي النظام",
            "wallpaper_default" to "رسومات واتساب الكلاسيكية",
            "wallpaper_teal" to "أخضر واتساب الزمردي",
            "wallpaper_navy" to "أزرق كحلي داكن",
            "wallpaper_amber" to "عنبري دافئ",
            "wallpaper_sky" to "سماوي هادئ",
            "manage_storage" to "إدارة التخزين",
            "network_usage" to "استخدام الشبكة",
            "security_keys" to "مفاتيح الأمان المقاومة للكم",
            "passkeys" to "مفاتيح المرور (Passkeys)",
            "app_lock" to "قفل التطبيق ببصمة الإصبع",
            "read_receipts" to "مؤشرات قراءة الرسائل (علامات الصح الزرقاء)",
            "end_to_end_encrypted" to "رسائلك ومكالماتك مشفرة تماماً بين الطرفين. لا أحد خارج هذه الدردشة، ولا حتى Adam Dev، يستطيع قراءتها أو الاستماع إليها.",
            "meta_footer" to "من Adam Dev",
            "done" to "تم",
            "cancel" to "إلغاء",
            "save" to "حفظ",
            "close" to "إغلاق"
        ),
        "en" to mapOf(
            "app_name" to "Adam Signal",
            "app_subtitle" to "End-to-End Encrypted by Adam Dev",
            "chats" to "Chats",
            "calls" to "Calls",
            "stories" to "Updates",
            "settings" to "Settings",
            "all" to "All",
            "pinned" to "Pinned",
            "unread" to "Unread",
            "direct" to "Direct",
            "groups" to "Groups",
            "search_hint" to "Search chats & messages...",
            "new_chat" to "New chat",
            "new_group" to "New group",
            "new_broadcast" to "New broadcast",
            "starred_messages" to "Starred messages",
            "linked_devices" to "Linked devices",
            "account" to "Account",
            "account_subtitle" to "Security notifications, passkeys, change number",
            "privacy" to "Privacy",
            "privacy_subtitle" to "Last seen, screen lock, disappearing messages timer",
            "chats_settings" to "Chats",
            "chats_settings_subtitle" to "Theme, wallpapers, chat history, backup",
            "notifications" to "Notifications",
            "notifications_subtitle" to "Message and group tones, vibrate, high priority",
            "storage_and_data" to "Storage and data",
            "storage_and_data_subtitle" to "Network usage, storage management, auto-download",
            "app_language" to "App language",
            "app_language_subtitle" to "English (device's language)",
            "help" to "Help",
            "help_subtitle" to "Help center, contact us, privacy policy & terms",
            "invite_friend" to "Invite a friend",
            "profile" to "Profile",
            "profile_and_settings" to "Profile & Settings",
            "sign_out" to "Sign out",
            "about_status" to "About",
            "default_status" to "Hey there! I am using Adam Signal 🛡️",
            "phone_number" to "Phone number",
            "username" to "Username",
            "verified_account" to "Verified Account",
            "creator_badge" to "Creator & Security Architect",
            "qr_code" to "QR code",
            "my_code" to "My Code",
            "scan_code" to "Scan Code",
            "share_code" to "Share Code",
            "reset_code" to "Reset QR Code",
            "qr_description" to "Your personal QR code is private. When scanned, others can start an end-to-end encrypted chat with you.",
            "star" to "Star",
            "unstar" to "Unstar",
            "reply" to "Reply",
            "forward" to "Forward",
            "copy" to "Copy text",
            "delete" to "Delete message",
            "typing" to "typing...",
            "online" to "Online",
            "offline" to "Offline",
            "type_a_message" to "Type a message...",
            "hold_to_record" to "Tap to record voice",
            "recording" to "Recording audio...",
            "safety_number" to "Safety Number",
            "disappearing_messages" to "Disappearing messages",
            "chat_wallpaper" to "Chat wallpaper",
            "clear_chat" to "Clear chat",
            "no_starred_messages" to "No starred messages yet",
            "starred_hint" to "Long-press on any message in any chat to star it, so you can easily find it later.",
            "theme" to "Theme",
            "theme_light" to "Light",
            "theme_dark" to "Dark",
            "theme_system" to "System default",
            "wallpaper_default" to "Classic WhatsApp Doodles",
            "wallpaper_teal" to "Emerald WhatsApp Teal",
            "wallpaper_navy" to "Deep Midnight Navy",
            "wallpaper_amber" to "Warm Amber",
            "wallpaper_sky" to "Calm Sky Blue",
            "manage_storage" to "Manage storage",
            "network_usage" to "Network usage",
            "security_keys" to "Quantum-Safe Encryption Keys",
            "passkeys" to "Passkeys",
            "app_lock" to "App lock with biometric fingerprint",
            "read_receipts" to "Read receipts (Blue ticks)",
            "end_to_end_encrypted" to "Messages and calls are end-to-end encrypted. No one outside of this chat, not even Adam Dev, can read or listen to them.",
            "meta_footer" to "from Adam Dev",
            "done" to "Done",
            "cancel" to "Cancel",
            "save" to "Save",
            "close" to "Close"
        ),
        "fr" to mapOf(
            "app_name" to "Adam Signal",
            "app_subtitle" to "Chiffrement de bout en bout par Adam Dev",
            "chats" to "Discussions",
            "calls" to "Appels",
            "stories" to "Actus",
            "settings" to "Paramètres",
            "all" to "Tous",
            "pinned" to "Épinglés",
            "unread" to "Non lus",
            "direct" to "Directs",
            "groups" to "Groupes",
            "search_hint" to "Rechercher...",
            "new_chat" to "Nouvelle discussion",
            "new_group" to "Nouveau groupe",
            "new_broadcast" to "Nouvelle diffusion",
            "starred_messages" to "Messages importants",
            "linked_devices" to "Appareils connectés",
            "account" to "Compte",
            "account_subtitle" to "Notifications de sécurité, passkeys, changer de numéro",
            "privacy" to "Confidentialité",
            "privacy_subtitle" to "Dernière présence, verrouillage, messages éphémères",
            "chats_settings" to "Discussions",
            "chats_settings_subtitle" to "Thème, fonds d'écran, sauvegarde",
            "notifications" to "Notifications",
            "notifications_subtitle" to "Sons, vibrations, haute priorité",
            "storage_and_data" to "Stockage et données",
            "storage_and_data_subtitle" to "Utilisation réseau, gestion du stockage",
            "app_language" to "Langue de l'application",
            "app_language_subtitle" to "Français",
            "help" to "Aide",
            "help_subtitle" to "Centre d'aide, contactez-nous",
            "invite_friend" to "Inviter un ami",
            "profile" to "Profil",
            "profile_and_settings" to "Profil & Paramètres",
            "sign_out" to "Déconnexion",
            "about_status" to "Actu",
            "default_status" to "Salut ! J'utilise Adam Signal 🛡️",
            "phone_number" to "Numéro de téléphone",
            "username" to "Nom d'utilisateur",
            "verified_account" to "Compte vérifié",
            "creator_badge" to "Créateur & Architecte sécurité",
            "qr_code" to "Code QR",
            "my_code" to "Mon code",
            "scan_code" to "Scanner le code",
            "share_code" to "Partager le code",
            "reset_code" to "Réinitialiser",
            "qr_description" to "Votre code QR est privé. D'autres peuvent le scanner pour démarrer une discussion chiffrée.",
            "star" to "Important",
            "unstar" to "Retirer",
            "reply" to "Répondre",
            "forward" to "Transférer",
            "copy" to "Copier",
            "delete" to "Supprimer",
            "typing" to "écrit...",
            "online" to "En ligne",
            "offline" to "Hors ligne",
            "type_a_message" to "Écrire un message...",
            "hold_to_record" to "Enregistrer audio",
            "recording" to "Enregistrement...",
            "safety_number" to "Numéro de sécurité",
            "disappearing_messages" to "Messages éphémères",
            "chat_wallpaper" to "Fond d'écran",
            "clear_chat" to "Effacer la discussion",
            "no_starred_messages" to "Aucun message important pour l'instant",
            "starred_hint" to "Appuyez longuement sur un message pour l'ajouter aux messages importants.",
            "theme" to "Thème",
            "theme_light" to "Clair",
            "theme_dark" to "Sombre",
            "theme_system" to "Système",
            "manage_storage" to "Gérer le stockage",
            "network_usage" to "Utilisation réseau",
            "security_keys" to "Clés quantiques",
            "app_lock" to "Verrouillage par empreinte",
            "read_receipts" to "Confirmations de lecture",
            "meta_footer" to "de Adam Dev",
            "done" to "Terminé",
            "cancel" to "Annuler",
            "save" to "Enregistrer",
            "close" to "Fermer"
        ),
        "es" to mapOf(
            "app_name" to "Adam Signal",
            "app_subtitle" to "Cifrado de extremo a extremo por Adam Dev",
            "chats" to "Chats",
            "calls" to "Llamadas",
            "stories" to "Novedades",
            "settings" to "Ajustes",
            "all" to "Todos",
            "pinned" to "Fijados",
            "unread" to "No leídos",
            "direct" to "Directos",
            "groups" to "Grupos",
            "search_hint" to "Buscar...",
            "new_chat" to "Nuevo chat",
            "new_group" to "Nuevo grupo",
            "new_broadcast" to "Nueva difusión",
            "starred_messages" to "Mensajes destacados",
            "linked_devices" to "Dispositivos vinculados",
            "account" to "Cuenta",
            "account_subtitle" to "Notificaciones de seguridad, passkeys, cambiar número",
            "privacy" to "Privacidad",
            "privacy_subtitle" to "Hora de última vez, bloqueo, mensajes temporales",
            "chats_settings" to "Chats",
            "chats_settings_subtitle" to "Tema, fondos de pantalla, copia de seguridad",
            "notifications" to "Notificaciones",
            "notifications_subtitle" to "Tonos de mensajes y grupos, vibración",
            "storage_and_data" to "Almacenamiento y datos",
            "storage_and_data_subtitle" to "Uso de red, administración de almacenamiento",
            "app_language" to "Idioma de la aplicación",
            "app_language_subtitle" to "Español",
            "help" to "Ayuda",
            "help_subtitle" to "Centro de ayuda, contáctanos",
            "invite_friend" to "Invitar a un amigo",
            "profile" to "Perfil",
            "profile_and_settings" to "Perfil y Ajustes",
            "sign_out" to "Cerrar sesión",
            "about_status" to "Info.",
            "default_status" to "¡Hola! Estoy usando Adam Signal 🛡️",
            "phone_number" to "Número de teléfono",
            "username" to "Nombre de usuario",
            "verified_account" to "Cuenta verificada",
            "creator_badge" to "Creador y Arquitecto de Seguridad",
            "qr_code" to "Código QR",
            "my_code" to "Mi código",
            "scan_code" to "Escanear código",
            "share_code" to "Compartir código",
            "reset_code" to "Restablecer código",
            "qr_description" to "Tu código QR es privado. Al escanearlo, otros pueden iniciar un chat cifrado contigo.",
            "star" to "Destacar",
            "unstar" to "No destacar",
            "reply" to "Responder",
            "forward" to "Reenviar",
            "copy" to "Copiar",
            "delete" to "Eliminar",
            "typing" to "escribiendo...",
            "online" to "En línea",
            "offline" to "Desconectado",
            "type_a_message" to "Escribe un mensaje...",
            "hold_to_record" to "Mantén presionado para grabar",
            "recording" to "Grabando...",
            "safety_number" to "Número de seguridad",
            "disappearing_messages" to "Mensajes temporales",
            "chat_wallpaper" to "Fondo de pantalla",
            "clear_chat" to "Vaciar chat",
            "no_starred_messages" to "No hay mensajes destacados aún",
            "starred_hint" to "Mantén presionado cualquier mensaje para destacarlo.",
            "theme" to "Tema",
            "theme_light" to "Claro",
            "theme_dark" to "Oscuro",
            "theme_system" to "Predeterminado del sistema",
            "manage_storage" to "Administrar almacenamiento",
            "network_usage" to "Uso de red",
            "security_keys" to "Claves cuánticas",
            "app_lock" to "Bloqueo con huella dactilar",
            "read_receipts" to "Confirmaciones de lectura",
            "meta_footer" to "de Adam Dev",
            "done" to "Listo",
            "cancel" to "Cancelar",
            "save" to "Guardar",
            "close" to "Cerrar"
        ),
        "de" to mapOf(
            "app_name" to "Adam Signal",
            "app_subtitle" to "Ende-zu-Ende verschlüsselt von Adam Dev",
            "chats" to "Chats",
            "calls" to "Anrufe",
            "stories" to "Aktuelles",
            "settings" to "Einstellungen",
            "all" to "Alle",
            "pinned" to "Fixiert",
            "unread" to "Ungelesen",
            "direct" to "Direkt",
            "groups" to "Gruppen",
            "search_hint" to "Suchen...",
            "new_chat" to "Neuer Chat",
            "new_group" to "Neue Gruppe",
            "new_broadcast" to "Neuer Broadcast",
            "starred_messages" to "Mit Stern markiert",
            "linked_devices" to "Verknüpfte Geräte",
            "account" to "Konto",
            "account_subtitle" to "Sicherheitsbenachrichtigungen, Passkeys",
            "privacy" to "Datenschutz",
            "privacy_subtitle" to "Zuletzt online, Bildschirmsperre, Selbstlöschende Nachrichten",
            "chats_settings" to "Chats",
            "chats_settings_subtitle" to "Design, Chat-Hintergrund, Backup",
            "notifications" to "Benachrichtigungen",
            "notifications_subtitle" to "Nachrichtentöne, Vibration",
            "storage_and_data" to "Speicher und Daten",
            "storage_and_data_subtitle" to "Netzwerknutzung, Speicher verwalten",
            "app_language" to "App-Sprache",
            "app_language_subtitle" to "Deutsch",
            "help" to "Hilfe",
            "help_subtitle" to "Hilfebereich, Kontaktiere uns",
            "invite_friend" to "Freund einladen",
            "profile" to "Profil",
            "profile_and_settings" to "Profil & Einstellungen",
            "sign_out" to "Abmelden",
            "about_status" to "Info",
            "default_status" to "Hallo! Ich benutze Adam Signal 🛡️",
            "phone_number" to "Telefonnummer",
            "username" to "Benutzername",
            "verified_account" to "Verifiziertes Konto",
            "creator_badge" to "Schöpfer & Sicherheitsarchitekt",
            "qr_code" to "QR-Code",
            "my_code" to "Mein Code",
            "scan_code" to "Code scannen",
            "share_code" to "Code teilen",
            "reset_code" to "Code zurücksetzen",
            "qr_description" to "Dein QR-Code ist privat. Andere können ihn scannen, um einen Chat zu starten.",
            "star" to "Mit Stern markieren",
            "unstar" to "Stern entfernen",
            "reply" to "Antworten",
            "forward" to "Weiterleiten",
            "copy" to "Kopieren",
            "delete" to "Löschen",
            "typing" to "tippt...",
            "online" to "Online",
            "offline" to "Offline",
            "type_a_message" to "Nachricht schreiben...",
            "hold_to_record" to "Halten zum Aufnehmen",
            "recording" to "Aufnahme läuft...",
            "safety_number" to "Sicherheitsnummer",
            "disappearing_messages" to "Selbstlöschende Nachrichten",
            "chat_wallpaper" to "Chat-Hintergrund",
            "clear_chat" to "Chat leeren",
            "no_starred_messages" to "Noch keine mit Stern markierten Nachrichten",
            "starred_hint" to "Halte eine Nachricht gedrückt, um sie mit einem Stern zu markieren.",
            "theme" to "Design",
            "theme_light" to "Hell",
            "theme_dark" to "Dunkel",
            "theme_system" to "Systemstandard",
            "manage_storage" to "Speicher verwalten",
            "network_usage" to "Netzwerknutzung",
            "security_keys" to "Quantensichere Schlüssel",
            "app_lock" to "Fingerabdruck-Sperre",
            "read_receipts" to "Lesebestätigungen",
            "meta_footer" to "von Adam Dev",
            "done" to "Fertig",
            "cancel" to "Abbrechen",
            "save" to "Speichern",
            "close" to "Schließen"
        ),
        "tr" to mapOf(
            "app_name" to "Adam Signal",
            "app_subtitle" to "Adam Dev tarafından Uçtan Uca Şifreli",
            "chats" to "Sohbetler",
            "calls" to "Aramalar",
            "stories" to "Güncellemeler",
            "settings" to "Ayarlar",
            "all" to "Tümü",
            "pinned" to "Sabitlenmiş",
            "unread" to "Okunmamış",
            "direct" to "Doğrudan",
            "groups" to "Gruplar",
            "search_hint" to "Ara...",
            "new_chat" to "Yeni sohbet",
            "new_group" to "Yeni grup",
            "new_broadcast" to "Yeni toplu mesaj",
            "starred_messages" to "Yıldızlı mesajlar",
            "linked_devices" to "Bağlı cihazlar",
            "account" to "Hesap",
            "account_subtitle" to "Güvenlik bildirimleri, geçiş anahtarları",
            "privacy" to "Gizlilik",
            "privacy_subtitle" to "Son görülme, ekran kilidi, süreli mesajlar",
            "chats_settings" to "Sohbetler",
            "chats_settings_subtitle" to "Tema, duvar kağıtları, sohbet geçmişi",
            "notifications" to "Bildirimler",
            "notifications_subtitle" to "Mesaj sesleri, titreşim, yüksek öncelik",
            "storage_and_data" to "Depolama ve veriler",
            "storage_and_data_subtitle" to "Ağ kullanımı, depolama yönetimi",
            "app_language" to "Uygulama dili",
            "app_language_subtitle" to "Türkçe",
            "help" to "Yardım",
            "help_subtitle" to "Yardım merkezi, bize ulaşın",
            "invite_friend" to "Bir arkadaşını davet et",
            "profile" to "Profil",
            "profile_and_settings" to "Profil ve Ayarlar",
            "sign_out" to "Çıkış yap",
            "about_status" to "Hakkımda",
            "default_status" to "Merhaba! Adam Signal kullanıyorum 🛡️",
            "phone_number" to "Telefon numarası",
            "username" to "Kullanıcı adı",
            "verified_account" to "Doğrulanmış Hesap",
            "creator_badge" to "Kurucu ve Güvenlik Mimarı",
            "qr_code" to "QR kodu",
            "my_code" to "Kodum",
            "scan_code" to "Kodu Tara",
            "share_code" to "Kodu Paylaş",
            "reset_code" to "Kodu Sıfırla",
            "qr_description" to "Kişisel QR kodunuz gizlidir. Başkaları tarayarak şifreli sohbet başlatabilir.",
            "star" to "Yıldızla",
            "unstar" to "Yıldızı kaldır",
            "reply" to "Cevapla",
            "forward" to "İlet",
            "copy" to "Kopyala",
            "delete" to "Sil",
            "typing" to "yazıyor...",
            "online" to "Çevrimiçi",
            "offline" to "Çevrimdışı",
            "type_a_message" to "Mesaj yazın...",
            "hold_to_record" to "Ses kaydı için basılı tutun",
            "recording" to "Kaydediliyor...",
            "safety_number" to "Güvenlik Numarası",
            "disappearing_messages" to "Süreli mesajlar",
            "chat_wallpaper" to "Sohbet duvar kağıdı",
            "clear_chat" to "Sohbeti temizle",
            "no_starred_messages" to "Henüz yıldızlı mesaj yok",
            "starred_hint" to "Herhangi bir sohbette bir mesaja uzun basarak yıldızlayabilirsiniz.",
            "theme" to "Tema",
            "theme_light" to "Açık",
            "theme_dark" to "Koyu",
            "theme_system" to "Sistem varsayılanı",
            "manage_storage" to "Depolamayı yönet",
            "network_usage" to "Ağ kullanımı",
            "security_keys" to "Kuantum Güvenli Anahtarlar",
            "app_lock" to "Parmak izi kilidi",
            "read_receipts" to "Okundu bilgisi",
            "meta_footer" to "Adam Dev tarafından",
            "done" to "Bitti",
            "cancel" to "İptal",
            "save" to "Kaydet",
            "close" to "Kapat"
        )
    )

    fun getString(key: String): String {
        val lang = _currentLanguage.value.code
        return translations[lang]?.get(key)
            ?: translations["en"]?.get(key)
            ?: key
    }
}
